# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-backport-scarthgap"
BBFILE_PATTERN_meta-backport-scarthgap = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-backport-scarthgap = "10"

LAYERDEPENDS_meta-backport-scarthgap = "core rauc"
LAYERSERIES_COMPAT_meta-backport-scarthgap = "scarthgap"
