# SPDX-License-Identifier: LGPL-2.1-only
# SPDX-FileCopyrightText: Copyright 2026 Gaël PORTAY

header:
  version: 2
local_conf_header:
  image-fstypes-efi-disk-dmverity-bootloader-config: |
    WKS_FILE ?= "${@bb.utils.contains('DM_VERITY_SEPARATE_HASH', '1', 'efi-disk-dmverity-hash-bootloader-config.wks.in', 'efi-disk-dmverity-bootloader-config.wks.in', d)} "
